### PR TITLE
TypeScript Parser Implementation

### PR DESCRIPTION
**Pull request by Denny09310**
This PR aims to merge the `new-parser` branch with the `main` branch to leverage the new features provided by .NET 8. Additionally, we have replaced the old regex-based parser with a new TypeScript parser, ensuring enhanced performance and maintainability. 

#### Changes Made:
1. **Merged `new-parser` Branch with `main`**:
    - Integrated the latest features and improvements from .NET 8.
    - Resolved merge conflicts to ensure compatibility with the `main` branch.

2. **Replaced Old Regex Parser with New TypeScript Parser**:
    - Removed the legacy regex parser implementation.
    - Integrated a new TypeScript parser for improved parsing capabilities.
    - Updated the relevant code sections to utilize the new parser.

3. **Testing and Verification**:
    - Executed all unit and integration tests to validate the changes.
    - Confirmed that all tests pass, ensuring the new parser works correctly.

#### Benefits:
- **Enhanced Performance**: The new TypeScript parser is more efficient and maintainable compared to the old regex-based implementation.
- **Modern Features**: Leveraging .NET 8 features enhances the application's performance and provides access to the latest framework improvements.
- **Code Quality**: Improved parsing logic with the new TypeScript parser, reducing potential bugs and increasing maintainability.

#### Testing:
- **Unit Tests**: All existing unit tests were run to ensure no regression issues were introduced. _(This based on the tests done, there's much work to do to say that there are no potential regression issues)_
- **Integration Tests**: Comprehensive integration tests were executed to verify the end-to-end functionality with the new parser.
- **Manual Testing**: Additional manual testing was conducted on critical paths to ensure stability and correctness.

#### How to Review:
1. **Code Changes**:
    - Review the commit history for detailed changes.
    - Pay special attention to the parsing logic modifications and test updates.

2. **Testing**:
    - Check the test results to confirm all tests pass.
    - Run additional tests if needed to verify specific scenarios.

3. **Documentation**:
    - Ensure that any relevant documentation is updated to reflect the changes, especially in areas related to the new parser.

---

#### Checklist:
- [x] Merged `new-parser` branch with `main`.
- [x] Replaced old regex parser with new TypeScript parser.
- [x] Verified all tests pass.
- [x] Updated documentation as needed.

### CODE REVIEW

**Comment by IEvangelist** [comment]
Hi @Denny09310 - since this is such a large change and based on a branch I already had let's target a PR to that branch, so that I can pull it down and test it out too.

**Comment by Denny09310** [comment]
> Hi @Denny09310 - since this is such a large change and based on a branch I already had let's target a PR to that branch, so that I can pull it down and test it out too.

Yes, sorry I haven't noticed that I was branch 'develop', I usually use **git flow** so it creates the correct branch. I'll merge all the changes in the 'new-parser' branch and reopen the PR (if I've understood correctly). Plus I've noticed some errors in the "SpeechSynthesis" package (don't know if already were there) that I should address. I'll close this PR and recreate the one in the correct branch

**Comment by Denny09310** [comment]
> Hi @Denny09310 - since this is such a large change and based on a branch I already had let's target a PR to that branch, so that I can pull it down and test it out too.

Yes, sorry I haven't noticed that I was branch 'develop', I usually use **git flow** so it creates the correct branch. I've noticed some errors in the "SpeechSyntesis" package (I don't know if they were already present) that I should address asap

**Review by IEvangelist — APPROVED** [review]
Wow! That was a lot to review!! I really appreciate this. Before it goes to `main`, we'll need to rebase with `main` first - and there will be merge conflicts.

**Pull request merged**
